jobs:
  include:
  - stage: validate
    name: validate GitHub OAuth token has sufficient scope to release
    script:
    - echo "===== job validate script:"
    - OWNER="$(echo $TRAVIS_REPO_SLUG | cut -d/ -f1)"
    - echo $TRAVIS_REPO_SLUG | wc -c
    - echo $GITHUB_OAUTH_TOKEN | wc -c
    - echo $TRAVIS_SECURE_ENV_VARS
    - 'curl -H "Authorization: token ${GITHUB_OAUTH_TOKEN}" "https://api.github.com/users/$OWNER"
      -I'
    - 'curl -H "Authorization: token ${GITHUB_OAUTH_TOKEN}" "https://api.github.com/users/$OWNER"
      -I | grep ^X-OAuth-Scopes'
  - stage: deploy
    if: fork = false AND tag IS present
    script:
    - 'echo "===== job script: OK"'
    deploy:
    - name: deploy (script, tags = true)
      provider: script
      script: 'echo "=====***** provider script: ok (tags = true)"'
      on:
        tags: true
    - provider: releases
      api_key: $GITHUB_OAUTH_TOKEN
      skip_cleanup: true
      on:
        tags: true
        condition: "($SKIP_FORGE_PUBLISH != true)"
